### ISSUE TITLE
Problem when pulling image from ECR

### ISSUE THREAD

**Issue by earthling42** [synthesis-labs/polaris#6]
Yesterday I managed to get our image into ECR and changed the yaml files to pull it from there instead of docker hub.

Something seems to have gone wrong with the pull. Could you guys please investigate and advise if this is a bug or pebcak?

$ kubectl.exe get pods --all-namespaces
NAMESPACE                   NAME                                         READY     STATUS             RESTARTS   AGE
docker                      compose-74649b4db6-mbg59                     1/1       Running            0          22h
docker                      compose-api-7c7bb4995b-bvq4v                 1/1       Running            0          22h
kube-system                 etcd-docker-for-desktop                      1/1       Running            20         18d
kube-system                 kube-apiserver-docker-for-desktop            1/1       Running            27         18d
kube-system                 kube-controller-manager-docker-for-desktop   1/1       Running            27         18d
kube-system                 kube-dns-86f4d74b45-dlvjt                    3/3       Running            67         18d
kube-system                 kube-proxy-9qskz                             1/1       Running            20         18d
kube-system                 kube-scheduler-docker-for-desktop            1/1       Running            26         18d

>> Problem child >>nedbank-dfl-email-routing   emailrouting-fb789b47f-695jt                 0/1       ImagePullBackOff   0          1m<<<<<

nedbank-dfl-email-routing   emailrouting-mysql-6b9656f999-p8jxm          1/1       Running            0          1m

Regards

Albert

**Comment by tjaard123** [comment]
Howzit Albert, sounds like stock k8s fun.

Use `$ kubectl desribe pod <pod>` for more info on why the pull is failing.

**Comment by drshade** [comment]
Fixed? Can we close?
